# Generated by Django 2.2.8 on 2020-01-20 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Documentation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(help_text='Category of this documentation whether it is for Flight deck , cabin crew , maintenance ...', max_length=100)),
                ('group', models.CharField(help_text='depending on the document it can be an airplane specific doc or other ex: Boeing ', max_length=100)),
                ('type', models.CharField(help_text='this is to specify the type of Airplane the Doc is specific to ex: B777', max_length=100)),
                ('folder', models.CharField(help_text='The title of the folder containing the documentation ex: FCOM', max_length=100)),
                ('file', models.FileField(help_text='This is usualy a PDF file, that needs to be protected against downloads', upload_to='')),
            ],
        ),
    ]
