# Generated by Django 2.2.8 on 2020-01-20 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentation', '0002_auto_20200120_0425'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentation',
            name='publish_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='documentation',
            name='title',
            field=models.CharField(default='Document', help_text='Documentation Title', max_length=100),
        ),
    ]
