# Generated by Django 2.2.8 on 2020-01-30 17:51

from django.db import migrations, models
import documentation.models


class Migration(migrations.Migration):

    dependencies = [
        ('documentation', '0003_auto_20200120_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentation',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to=documentation.models.set_filename, verbose_name='Cover Image'),
        ),
        migrations.AddField(
            model_name='documentation',
            name='description',
            field=models.TextField(default='', help_text='The description of the documentation'),
        ),
        migrations.AddField(
            model_name='documentation',
            name='price',
            field=models.CharField(default='0', help_text='The price of the documentation', max_length=10),
        ),
    ]
