# Generated by Django 2.2.8 on 2020-02-03 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentation', '0005_purchaselist'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentation',
            name='new_flag',
            field=models.BooleanField(default=False),
        ),
    ]
