# Generated by Django 2.2.8 on 2020-02-03 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documentation', '0006_documentation_new_flag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documentation',
            old_name='new_flag',
            new_name='new_document',
        ),
    ]
