"""
Django settings for briteleader project.

Generated by 'django-admin startproject' using Django 2.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import os

from django.utils.translation import ugettext_lazy as _
import django_heroku
from .secret import get_secret
import datetime
# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = get_secret()

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('IN_PRODUCTION', 'False') == 'False'


ALLOWED_HOSTS = ['*']
gettext = lambda s: s

LANGUAGES = [
    ('en', gettext('English')),
    ('fr', gettext('French')),
    ('es', gettext('Spanish')),
    ('pt', gettext('Portuguese')),
]

SITE_ID = int(os.environ.get('SITE_ID', 1))
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
# SECURE_SSL_REDIRECT = True

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'rest_framework_swagger',
    'rest_auth',
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    # 'allauth.socialaccount.providers.facebook',
    'rest_auth.registration',
    'taggit',
    'myauth',
    'bootstrap4',
    'company',
    'professional',
    'drf_yasg',
    'corsheaders',
    'mainweb',
    'logbook',
    'myuser',
    'mathfilters',
    'django_seed',
    # 'modeltranslation',
    'djmoney',
    'fcm_django',
    'articles',
    'jobs',
    'bids',
    'webpack_loader',
    'frontend',
    'documentation',
    'chat',
    'channels',
    "djstripe",
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    #'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'myuser.middlewares.ActivityMiddleware'

]

ROOT_URLCONF = 'briteleader.urls'

CORS_ORIGIN_ALLOW_ALL = True


TEMPLATES = [
    {
       'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'templates')
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            "hosts": [('127.0.0.1', 6379)],
        },
    },
}
ASGI_APPLICATION = "briteleader.routing.application"
WSGI_APPLICATION = 'briteleader.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db59.sqlite3'),
    }
}
# pdf module
WKHTMLTOPDF_CMD_OPTIONS = {
    'quiet': True,
}

# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

LANGUAGE_CODE = 'en'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/




REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework_jwt.authentication.JSONWebTokenAuthentication',
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.BasicAuthentication',
        'django.contrib.auth.backends.ModelBackend',
    ),
    'DEFAULT_PERMISSION_CLASS' : (
        'rest_framework.permissions.DjangoModelPermissionsOrAnonReadOnly'
        'rest_framework.permissions.IsAuthenticated',
        'rest_framework.permissions.IsAuthenticatedOrReadOnly'
    ),
    'DEFAULT_FILTER_BACKENDS': ('django_filters.rest_framework.DjangoFilterBackend',),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.LimitOffsetPagination',#'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 40
}

AUTHENTICATION_BACKENDS = (
    'allauth.account.auth_backends.AuthenticationBackend',
)

SOCIALACCOUNT_PROVIDERS_ADAPTERS = {
    'facebook': 'allauth.socialaccount.providers.facebook.views.FacebookOAuth2Adapter',
    'google': 'allauth.socialaccount.providers.google.views.GoogleOAuth2Adapter'
}


SWAGGER_SETTINGS = {
    'SECURITY_DEFINITIONS': {
        'basic': {
            'type': 'basic'
        }
    },
    'DOC_EXPANSION': 'None',
}


#Allauth settings
ACCOUNT_ADAPTER = 'myauth.adapters.DefaultAccountAdapter'
AUTH_USER_MODEL = 'auth.User'
ACCOUNT_EMAIL_VERIFICATION = 'mandatory'
ACCOUNT_LOGIN_ON_EMAIL_CONFIRMATION = True
ACCOUNT_AUTHENTICATION_METHOD = 'email'
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_USERNAME_REQUIRED = False
SOCIALACCOUNT_EMAIL_REQUIRED = True
REST_AUTH_REGISTER_SERIALIZERS = {
        'REGISTER_SERIALIZER': 'myauth.serializers.RegisterSerializer',
}



EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

EMAIL_HOST = 'smtp.sendgrid.net'
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
EMAIL_PORT = 587
EMAIL_USE_TLS = True



ADMINS = [
    ('Omar', 'omarkounda@soleotogether.com')
]

LOCALE_PATHS = (
    os.path.join(BASE_DIR, 'locale'),
)


ACCOUNT_FORMS = {'signup': 'mainweb.forms.MyCustomSignupForm'}

#from briteleader.local import *

#******* HEROKU *********#
PAYPAL_PAYMENT_MODE = os.environ.get('PAYPAL_PAYMENT_MODE', 'sandbox') #"sandbox" / live
PAYPAL_PAYMENT_CLIENT_ID =  os.environ.get('PAYPAL_PAYMENT_CLIENT_ID', 'Aa1Ii468rMwBlJUOq4XHfd3bid1BY3PR-Kq9Nog4SONUY3Nd4Qib5X7ugW0P1KR1YpmqYKsvJwLN4Wb6')
PAYPAL_PAYMENT_CLIENT_SECRET = os.environ.get('PAYPAL_PAYMENT_CLIENT_SECRET', 'EHYNZBJBDqDSpDKGqSUnuBA4RGjFZxou0qdMMIKRuikSVsAbs8lEzwNNd0Ld2CQMveHwdxo4MOACfxs2')
#API SECRET KEY
# STRIPE_API_KEY = os.environ.get('STRIPE_API_KEY', 'sk_test_HFYyPTxwwgDSrsIIRThCmuWE')
# WEBHOOK SECRET EVENTS FROM ACCOUNT /api/subscription/webhook
# STRIPE_SIGNING_SECRET = os.environ.get('STRIPE_SIGNING_SECRET', 'whsec_gxfsyHvVCwvo9MDonJg5kMCbXVW3wigQ')
# WEBHOOK SECRET EVENTS FROM CONNECT APP /api/wallet/account/webhook
# STRIPE_ACCOUNT_WEBHOOK_SIGNING_SECRET = os.environ.get('STRIPE_ACCOUNT_WEBHOOK_SIGNING_SECRET', 'whsec_yrz8lOaiYkx7KX26pAEmv36pHVSl1D87')

STRIPE_TEST_PUBLIC_KEY = os.environ.get("STRIPE_TEST_PUBLIC_KEY", "pk_test_56gHGiWiSFd15FqUZ5rwu36s00qRYOaCez")
STRIPE_TEST_SECRET_KEY = os.environ.get("STRIPE_TEST_SECRET_KEY", "sk_test_aPBcus2JWHn4hbfBcP5qYV14009bBMSvn4")
STRIPE_LIVE_MODE = False  # Change to True in production
DJSTRIPE_WEBHOOK_SECRET = "whsec_xxx"

BROKER_URL = os.environ.get('REDIS_URL', 'redis://localhost')
CELERY_BROKER_URL = os.environ.get('REDIS_URL', 'redis://localhost')
GOOGLE_API_KEY = os.environ.get('GOOGLE_API_KEY', 'AIzaSyAxTdq3NRpHWXdRsDCAAKx4R4pK5wk3c8Q')

PAYPAL_PAYMENT_REDIRECT_URL = os.environ.get('PAYPAL_PAYMENT_REDIRECT_URL', "http://127.0.0.1:8080/dashboard/paypal_dialog")
PAYPAL_PAYMENT_CANCEL_URL = os.environ.get('PAYPAL_PAYMENT_CANCEL_URL', "http://localhost:3000/")
PAYPAL_SUBSCRIPTION_PAYMENT_REDIRECT_URL = os.environ.get('PAYPAL_SUBSCRIPTION_PAYMENT_REDIRECT_URL', "http://127.0.0.1:8080/dashboard/paypal_execute_subscription.html")
PAYPAL_SUBSCRIPTION_PAYMENT_CANCEL_URL = os.environ.get('PAYPAL_SUBSCRIPTION_PAYMENT_CANCEL_URL', 'http://127.0.0.1:8080/dashboard/paypal_subscription_dialog')
PAYPAL_WEBHOOK_ID = os.environ.get('PAYPAL_WEBHOOK_ID', '3PR735644J190505A')

FRONTEND_CONFIRMATION_URL = os.environ.get('FRONTEND_CONFIRMATION_URL', 'http://127.0.0.1:8080/user/verify-email')#'http://127.0.0.1:8080/user/verify-email'
MEDIA_LINK_PATH = os.environ.get('MEDIA_LINK_PATH', 'http://127.0.0.1:8000')#'http://127.0.0.1:8080/user/verify-email'


EMAIL_FROM = os.environ.get('EMAIL_FROM', 'admin@soleotogether.com')
SUPPORT_EMAIL = os.environ.get('SUPPORT_EMAIL', 'admin@soleotogether.com')
MARKETING_EMAIL = os.environ.get('MARKETING_EMAIL', 'admin@soleotogether.com')
SUPPORT_EMAIL_ADDRESS = os.environ.get('SUPPORT_EMAIL_ADDRESS', 'admin@soleotogether.com')
DEFAULT_FROM_EMAIL = os.environ.get('EMAIL_FROM', 'admin@soleotogether.com')
SERVER_EMAIL = MARKETING_EMAIL

ADMIN_EMAIL = os.environ.get('ADMIN_EMAIL', 'admin@soleotogether.com')
ADMIN_PHONE = os.environ.get('ADMIN_PHONE', '')

TWILIO_ACCOUNT_SID = os.environ.get('TWILIO_ACCOUNT_SID', '')
TWILIO_AUTH_TOKEN = os.environ.get('TWILIO_AUTH_TOKEN', '')
TWILIO_PHONE_NUMBER = os.environ.get('TWILIO_PHONE_NUMBER', '')

OPENEXCHANGERATES_API_KEY = os.environ.get('OPEN_EXCHANGE_RATES_APP_ID', '')

#*****LOCAL ENV***********

#BACKEND_LINK = 'https://soleo-backend.herokuapp.com/api/'
#DATABASE_URL= 'postgres://jaoaahwmkakxix:676a1d39c11a4e363ebfff616027e7e778113c7c6bca5043974df811b7a9718f@ec2-54-235-156-60.compute-1.amazonaws.com:5432/d9m6v903htgqg5'
#DISABLE_COLLECTSTATIC=  1
#EMAIL_HOST_PASSWORD= 'Soleo123#'
#EMAIL_HOST_USER= 'omarkounda@soleotogether.com'
#EMAIL_FROM = 'Soleo Together Notifications <no-reply@soleotogether.com>'
#SUPPORT_EMAIL = 'Soleo Together Support <support@soleotogether.com>'
#ADMIN_EMAIL = 'admin@soleotogether.com'
#ADMIN_PHONE = '+16167101725'
#MARKETING_EMAIL = 'Soleo Together Marketing <team@soleotogether.com>'
#FRONTEND_CONFIRMATION_URL= 'https://www.soleotogether.com/user/verify-email'
#GOOGLE_API_KEY= 'AIzaSyAxTdq3NRpHWXdRsDCAAKx4R4pK5wk3c8Q'
#IN_PRODUCTION=    True
#MEDIA_LINK_PATH=  'https://soleo-backend.herokuapp.com'
#PAYPAL_PAYMENT_CANCEL_URL= 'http://localhost:3000/'
#PAYPAL_PAYMENT_CLIENT_ID=  'AUIfnOwvrr6aIE6cgm4giUKkWSFRaX1X0AG7NLgu0Y38yx0PnztWRbhVq8mpJWbAfohhDcS1KvyB4cUX'
#PAYPAL_PAYMENT_CLIENT_SECRET=   'EDawykxnu6p3xZrQcVFM8-v3GGrRcaOSjk-mqi7SY_dhiivrXnWIQlAb_DFrLxKx0JXoT4CpYqEainNB'
#PAYPAL_PAYMENT_REDIRECT_URL=    'https://soleo-frontend-test.herokuapp.com/dashboard/paypal_dialog'
#PAYPAL_SUBSCRIPTION_PAYMENT_CANCEL_URL=   'https://soleo-frontend-test.herokuapp.com/dashboard/paypal_subscription_dialog'
#PAYPAL_SUBSCRIPTION_PAYMENT_REDIRECT_URL= 'https://soleo-frontend-test.herokuapp.com/dashboard/paypal_subscription_dialog'
#REDIS_URL=  'redis://h:p0f14c12c34def9ad62d4f618c4c6587be920cb5ab655c563bf710d763f50e70f@ec2-23-22-183-50.compute-1.amazonaws.com:64709'
#STRIPE_API_KEY= 'sk_test_HFYyPTxwwgDSrsIIRThCmuWE'
#TWILIO_ACCOUNT_SID = 'AC967645fbf5dd74333982422a5a856e29'
#TWILIO_AUTH_TOKEN = '1026a3c4e2732c27635087db2cfc142b'
#TWILIO_PHONE_NUMBER = '+14159806462'
#OPENEXCHANGERATES_API_KEY = '87c32b40889c47d9bae0112b2a63dbc1'

OPENEXCHANGERATES_BASE_CURRENCY = 'USD'


JWT_AUTH = {
    'JWT_ENCODE_HANDLER':
    'rest_framework_jwt.utils.jwt_encode_handler',

    'JWT_DECODE_HANDLER':
    'rest_framework_jwt.utils.jwt_decode_handler',

    'JWT_PAYLOAD_HANDLER':
    'rest_framework_jwt.utils.jwt_payload_handler',

    'JWT_PAYLOAD_GET_USER_ID_HANDLER':
    'rest_framework_jwt.utils.jwt_get_user_id_from_payload_handler',

    'JWT_RESPONSE_PAYLOAD_HANDLER':
    'rest_framework_jwt.utils.jwt_response_payload_handler',

    'JWT_SECRET_KEY': SECRET_KEY,
    'JWT_GET_USER_SECRET_KEY': None,
    'JWT_PUBLIC_KEY': None,
    'JWT_PRIVATE_KEY': None,
    'JWT_ALGORITHM': 'HS256',
    'JWT_VERIFY': True,
    'JWT_VERIFY_EXPIRATION': True,
    'JWT_LEEWAY': 0,
    'JWT_EXPIRATION_DELTA': datetime.timedelta(seconds=300),
    'JWT_AUDIENCE': None,
    'JWT_ISSUER': None,

    'JWT_ALLOW_REFRESH': False,
    'JWT_REFRESH_EXPIRATION_DELTA': datetime.timedelta(days=7),

    'JWT_AUTH_HEADER_PREFIX': 'JWT',
    'JWT_AUTH_COOKIE': None,

}

FCM_DJANGO_SETTINGS = {
        "APP_VERBOSE_NAME": "briteleader-app",
        "FCM_SERVER_KEY": os.environ.get('FIREBASE_SERVER_KEY', ''),
        "ONE_DEVICE_PER_USER": False,
        "DELETE_INACTIVE_DEVICES": False,
}


GLOBAL_VAL = []
from .statics import *
try:
    from .local import *
except ImportError as e:
    pass
django_heroku.settings(locals(), staticfiles=False)
LOGIN_REDIRECT_URL = "/"