# Generated by Django 2.2.8 on 2020-01-10 06:42

import company.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_partner', models.BooleanField(default=False, help_text='If we have company agreement with them')),
                ('is_authorized', models.BooleanField(default=False, help_text='if they paid access to data')),
                ('establish', models.DateField(blank=True, null=True)),
                ('employees', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyGeneralBenefits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_housing', models.BooleanField(default=False)),
                ('offer_id_tickets_self', models.BooleanField(default=True)),
                ('offer_id_tickets_family', models.BooleanField(default=True)),
                ('offer_id_tickets_extended_family', models.BooleanField(default=True)),
                ('offer_id_tickets_friends', models.BooleanField(default=True)),
                ('offer_education_allowance', models.BooleanField(default=False)),
                ('offer_end_of_service_benefits', models.BooleanField(default=False)),
                ('offer_pension', models.BooleanField(default=False)),
                ('offer_life_insurance', models.BooleanField(default=False)),
                ('offer_health_insurance_self', models.BooleanField(default=True)),
                ('offer_health_insurance_family', models.BooleanField(default=True)),
                ('offer_loss_of_license', models.BooleanField(default=True)),
                ('has_code_share_aggreement', models.BooleanField(default=False)),
                ('has_alliance', models.BooleanField(default=False)),
                ('alliance_name', models.CharField(blank=True, help_text='ex OneWorld, StarAlliance ...', max_length=200, null=True)),
                ('company', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='company.Company')),
            ],
        ),
        migrations.CreateModel(
            name='RequiredDocs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passport', models.BooleanField(default=True)),
                ('licence_copy', models.BooleanField(default=True)),
                ('resume', models.BooleanField(default=False)),
                ('recommendation_letter', models.BooleanField(default=False)),
                ('copy_logbook', models.BooleanField(default=False)),
                ('other', models.CharField(blank=True, help_text='To be specified', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SelectionProcess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interview', models.BooleanField(default=True)),
                ('simulator', models.BooleanField(default=True)),
                ('technical_exam', models.BooleanField(default=True)),
                ('group_assessment', models.BooleanField(default=False)),
                ('medical_check', models.BooleanField(default=False)),
                ('done_at_headquarter', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobRequirements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience', models.CharField(blank=True, help_text='Can be Number of years, Aircrafts experience, Flight hours ,position or combination of all', max_length=100, null=True)),
                ('qualifications', models.CharField(blank=True, max_length=100, null=True)),
                ('age_limit', models.CharField(blank=True, max_length=100, null=True)),
                ('education', models.CharField(blank=True, max_length=100, null=True)),
                ('other', models.CharField(blank=True, max_length=100, null=True)),
                ('documents_required', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.RequiredDocs')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('type', models.CharField(blank=True, help_text='Choices whether airline , catering ....', max_length=100, null=True)),
                ('type_of_operation', models.CharField(blank=True, help_text='Choices ex Charter, Low Cost, Regular', max_length=100, null=True)),
                ('aircraft_type', models.CharField(blank=True, help_text='Type of aircrafts operated by the airline ex. B777 - B787 as list', max_length=100, null=True)),
                ('aircraft_number', models.IntegerField(default=0)),
                ('destinations', models.CharField(blank=True, help_text='Many True, list of continents where they operate', max_length=100, null=True)),
                ('base', models.CharField(blank=True, help_text='city where the company is based', max_length=100, null=True)),
                ('aircraft_image', models.ImageField(blank=True, default='users/aircraft/blank-avatar.jpg', null=True, upload_to=company.models.set_aircraft_filename, verbose_name='cover image of aircraft')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='company.Company')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyJobOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(blank=True, max_length=250, null=True)),
                ('position_offered', models.CharField(blank=True, help_text='ex Captain B777', max_length=100, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('job_description', models.CharField(blank=True, max_length=10000, null=True)),
                ('salary', models.IntegerField(blank=True, default=0, null=True)),
                ('salary_interval', models.CharField(blank=True, help_text='per month / per year', max_length=10, null=True)),
                ('contract_type', models.CharField(blank=True, help_text='CDI (undetermined duration or CDD fix term', max_length=100, null=True)),
                ('contract_duration', models.CharField(blank=True, help_text='Choices are value or undetermined', max_length=10, null=True)),
                ('benefits', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='company.CompanyGeneralBenefits')),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='company.Company')),
                ('requirements', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.JobRequirements')),
                ('selection_process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.SelectionProcess')),
            ],
        ),
    ]
