# Generated by Django 2.2.2 on 2019-11-12 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OAuth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('clientId', models.CharField(max_length=100)),
                ('accessTokenUri', models.CharField(max_length=50)),
                ('authorizationUri', models.CharField(max_length=50)),
                ('redirectUri', models.CharField(max_length=150)),
                ('state', models.CharField(max_length=50)),
                ('scopes', models.CharField(max_length=50)),
                ('responseType', models.CharField(max_length=50)),
                ('loginpath', models.CharField(max_length=50)),
            ],
        ),
    ]
