# Generated by Django 2.2.8 on 2020-01-10 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=200)),
                ('description', models.TextField(default='')),
                ('position', models.CharField(blank=True, choices=[('P', 'Pilot'), ('C', 'Cabin Crew'), ('M', 'Maintenance'), ('O', 'Office')], max_length=2, null=True)),
                ('exp_lv', models.CharField(blank=True, choices=[('2', '2 years'), ('4', '4 years'), ('5', '5 years'), ('8', '8 years'), ('o', '8 years over')], max_length=2, null=True)),
                ('country', models.CharField(blank=True, max_length=20, null=True)),
                ('job_type', models.CharField(blank=True, choices=[('F', 'full time'), ('P', 'part time')], max_length=2, null=True)),
                ('rate', models.FloatField(default=0, max_length=20, null=True)),
                ('status', models.IntegerField(default=0, null=True)),
                ('publish_date', models.DateField(auto_now_add=True, null=True)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='company.Company')),
            ],
        ),
    ]
