# Generated by Django 2.2.8 on 2020-01-10 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_comments_userdd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='userdd',
        ),
    ]
