# Generated by Django 2.2.8 on 2020-02-04 18:17

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aircraft_type', models.CharField(blank=True, max_length=100)),
                ('aircraft_registration', models.CharField(blank=True, max_length=100)),
                ('is_single_engine_ac', models.BooleanField(default=False)),
                ('is_multi_engine_ac', models.BooleanField(default=False)),
                ('is_multi_pilot', models.BooleanField(default=False)),
                ('is_single_pilot', models.BooleanField(default=False)),
                ('is_jet_ac', models.BooleanField(default=False)),
                ('is_sim', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CrewMembers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('self_name', models.CharField(blank=True, help_text='This the User first_name + last_name object', max_length=100)),
                ('pic_name', models.CharField(blank=True, max_length=100)),
                ('first_officer_name', models.CharField(blank=True, max_length=100)),
                ('other_crew_2', models.CharField(blank=True, max_length=100)),
                ('other_crew_3', models.CharField(blank=True, max_length=100)),
                ('other_crew_4', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remarks', models.CharField(blank=True, max_length=1000, null=True)),
                ('event_description', models.CharField(blank=True, max_length=1000, null=True)),
                ('asr_filed', models.BooleanField(blank=True, default=False, null=True)),
                ('auto_land', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FlightConditions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_day_time', models.BooleanField(default=True)),
                ('is_night_time', models.BooleanField(default=False)),
                ('is_imc', models.BooleanField(default=False)),
                ('is_ifr', models.BooleanField(default=False)),
                ('is_pic', models.BooleanField(default=False)),
                ('is_copilot', models.BooleanField(default=False)),
                ('is_dual', models.BooleanField(default=False)),
                ('is_instructor', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='FlightData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('departure_airport', models.CharField(blank=True, max_length=100)),
                ('arrival_airport', models.CharField(blank=True, max_length=100)),
                ('take_off_time', models.TimeField(blank=True, null=True)),
                ('landing_time', models.TimeField(blank=True, null=True)),
                ('on_block_time', models.DurationField(blank=True, default=datetime.timedelta(0), null=True)),
                ('flight_time', models.DurationField(blank=True, default=datetime.timedelta(0), null=True)),
                ('block_departure', models.TimeField(blank=True, null=True)),
                ('block_arrive', models.TimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FlightHours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('single_engine_time', models.DurationField(default=datetime.timedelta(0))),
                ('multi_engine_time', models.DurationField(default=datetime.timedelta(0))),
                ('multi_pilot_time', models.DurationField(default=datetime.timedelta(0))),
                ('total_time', models.DurationField(default=datetime.timedelta(0))),
                ('night_flight_time', models.DurationField(default=datetime.timedelta(0))),
                ('ifr_flight_time', models.DurationField(default=datetime.timedelta(0))),
                ('pic_time', models.DurationField(blank=True, default=datetime.timedelta(0))),
                ('copilot_time', models.DurationField(blank=True, default=datetime.timedelta(0))),
                ('dual_time', models.DurationField(blank=True, default=datetime.timedelta(0))),
                ('instructor_time', models.DurationField(blank=True, default=datetime.timedelta(0))),
            ],
        ),
        migrations.CreateModel(
            name='PreviousExperience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('single_engine_hours_previous', models.DurationField(blank=True, default=datetime.timedelta(0))),
                ('multi_engine_hours_previous', models.DurationField(blank=True, default=datetime.timedelta(0))),
                ('multi_pilot_hours_previous', models.DurationField(blank=True, default=datetime.timedelta(0))),
                ('total_flight_hours_previous', models.DurationField(blank=True, default=datetime.timedelta(0))),
                ('total_night_hours_previous', models.DurationField(blank=True, default=datetime.timedelta(0))),
                ('total_ifr_hours_previous', models.DurationField(blank=True, default=datetime.timedelta(0))),
                ('total_pic_hours_previous', models.DurationField(blank=True, default=datetime.timedelta(0))),
                ('total_copilot_hours_previous', models.DurationField(blank=True, default=datetime.timedelta(0))),
                ('total_dual_hours_previous', models.DurationField(blank=True, default=datetime.timedelta(0))),
                ('total_instructor_hours_previous', models.DurationField(blank=True, default=datetime.timedelta(0))),
                ('total_simulator_hours_previous', models.DurationField(blank=True, default=datetime.timedelta(0))),
            ],
        ),
        migrations.CreateModel(
            name='Simulator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('simulator_date', models.DateField(blank=True, null=True)),
                ('simulator_type', models.CharField(blank=True, max_length=100, null=True)),
                ('simulator_duration', models.DurationField(blank=True, default=datetime.timedelta(0), null=True)),
                ('simulator_instructor', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TotalExperience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('single_engine_hours_actual', models.DurationField(blank=True, default=datetime.timedelta(0))),
                ('multi_engine_hours_actual', models.DurationField(blank=True, default=datetime.timedelta(0))),
                ('multi_pilot_hours_actual', models.DurationField(blank=True, default=datetime.timedelta(0))),
                ('total_flight_hours_actual', models.DurationField(blank=True, default=datetime.timedelta(0))),
                ('total_night_hours_actual', models.DurationField(blank=True, default=datetime.timedelta(0))),
                ('total_ifr_hours_actual', models.DurationField(blank=True, default=datetime.timedelta(0))),
                ('total_pic_hours_actual', models.DurationField(blank=True, default=datetime.timedelta(0))),
                ('total_copilot_hours_actual', models.DurationField(blank=True, default=datetime.timedelta(0))),
                ('total_dual_hours_actual', models.DurationField(blank=True, default=datetime.timedelta(0))),
                ('total_instructor_hours_actual', models.DurationField(blank=True, default=datetime.timedelta(0))),
                ('total_simulator_hours_actual', models.DurationField(blank=True, default=datetime.timedelta(0))),
            ],
        ),
        migrations.CreateModel(
            name='Pilot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_experience', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='logbook.TotalExperience')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aircraft_data', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='logbook.Aircraft')),
                ('crew_members_data', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='logbook.CrewMembers')),
                ('events_data', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='logbook.Events')),
                ('flight_conditions_data', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='logbook.FlightConditions')),
                ('flight_data', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='logbook.FlightData')),
                ('flight_hours_data', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='logbook.FlightHours')),
                ('pilot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='logbook.Pilot')),
                ('simulator_data', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='logbook.Simulator')),
            ],
        ),
    ]
