# Generated by Django 2.2.8 on 2020-02-04 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crewmembers',
            old_name='other_crew_4',
            new_name='other_crew_41',
        ),
    ]
