# Generated by Django 2.2.2 on 2019-11-12 18:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import myuser.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=250)),
                ('message', models.CharField(max_length=1000)),
                ('topic', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=20, null=True)),
                ('title_en', models.CharField(blank=True, max_length=20, null=True)),
                ('title_fr', models.CharField(blank=True, max_length=20, null=True)),
                ('title_es', models.CharField(blank=True, max_length=20, null=True)),
                ('title_pt', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('subscription_date', models.DateTimeField(auto_now=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('active_subscription', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, default='I', max_length=2, null=True)),
                ('avatar', models.ImageField(blank=True, default='users/avatar/blank-avatar.jpg', null=True, upload_to=myuser.models.set_filename, verbose_name='photo of profile')),
                ('company_name', models.CharField(blank=True, max_length=100, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('address_1', models.CharField(blank=True, max_length=150, verbose_name='address 1 ')),
                ('address_2', models.CharField(blank=True, max_length=150, verbose_name='address 2 ')),
                ('city', models.CharField(blank=True, max_length=20, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='Zip Code')),
                ('state', models.CharField(blank=True, max_length=20, null=True)),
                ('country', models.CharField(blank=True, max_length=20, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=100, null=True)),
                ('position', models.CharField(blank=True, choices=[('P', 'Pilot'), ('C', 'Cabin Crew'), ('M', 'Maintenance'), ('O', 'Office'), ('B', 'Business')], max_length=2, null=True)),
                ('send_sms_user', models.BooleanField(default=True)),
                ('is_restricted_user', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profile',
            },
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=20)),
                ('path', models.CharField(max_length=100)),
                ('method', models.CharField(max_length=10)),
                ('time', models.DateTimeField(auto_now=True)),
                ('location_latitude', models.FloatField(default=0, max_length=20, null=True)),
                ('location_longitude', models.FloatField(default=0, max_length=20, null=True)),
                ('city', models.CharField(max_length=50)),
                ('body', models.CharField(max_length=1000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
