# Generated by Django 2.2.2 on 2019-11-14 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0002_auto_20191112_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='type',
            field=models.CharField(blank=True, choices=[('I', 'individual'), ('C', 'company')], default='I', max_length=2),
        ),
    ]
