# Generated by Django 2.2.7 on 2019-11-25 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0003_auto_20191114_1024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='languages',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='languages',
            name='title_es',
        ),
        migrations.RemoveField(
            model_name='languages',
            name='title_fr',
        ),
        migrations.RemoveField(
            model_name='languages',
            name='title_pt',
        ),
    ]
