# Generated by Django 2.2.8 on 2020-01-06 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0004_auto_20191125_0500'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='follower',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='following',
            field=models.IntegerField(default=0),
        ),
    ]
