# Generated by Django 2.2.8 on 2020-01-06 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0005_auto_20200106_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='desc',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
