# Generated by Django 2.2.8 on 2020-01-07 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0007_auto_20200106_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='overview',
            field=models.TextField(default=''),
        ),
    ]
