# Generated by Django 2.2.8 on 2020-01-09 04:12

from django.db import migrations, models
import myuser.models


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0008_userprofile_overview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='cover',
            field=models.ImageField(blank=True, default='users/cover/blank-avatar.jpg', null=True, upload_to=myuser.models.set_cover_filename, verbose_name='cover image of profile'),
        ),
    ]
