# Generated by Django 2.2.8 on 2020-01-21 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0009_auto_20200109_0412'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_subscribed',
            field=models.BooleanField(default=False),
        ),
    ]
