# Generated by Django 2.2.8 on 2020-01-10 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
        ('professional', '0010_professionaldocs_pro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bids',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=200)),
                ('description', models.TextField(default='')),
                ('jobs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.Jobs')),
                ('professional', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='professional.Professional')),
            ],
        ),
    ]
