# Generated by Django 2.2.2 on 2019-11-14 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('professional', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competenceprofile',
            name='pro',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='professional.Professional'),
        ),
        migrations.AlterField(
            model_name='educationprofile',
            name='pro',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='professional.Professional'),
        ),
        migrations.AlterField(
            model_name='experienceprofile',
            name='pro',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='professional.Professional'),
        ),
    ]
