# Generated by Django 2.2.7 on 2019-11-25 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professional', '0002_auto_20191114_1238'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessionalDocs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passport', models.FileField(null=True, upload_to='')),
                ('license', models.FileField(null=True, upload_to='')),
                ('medical', models.FileField(null=True, upload_to='')),
                ('recommendation_letter', models.FileField(null=True, upload_to='')),
                ('employer_letter', models.FileField(null=True, upload_to='')),
                ('logbook', models.FileField(null=True, upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='professional',
            name='is_subscribed',
            field=models.BooleanField(default=False),
        ),
    ]
