# Generated by Django 2.2.7 on 2019-12-13 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professional', '0006_auto_20191210_0546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationprofile',
            name='end_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='educationprofile',
            name='start_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='experienceprofile',
            name='end_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='experienceprofile',
            name='start_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
