# Generated by Django 2.2.7 on 2019-12-14 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professional', '0007_auto_20191213_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='professional',
            name='skills',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='educationprofile',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='educationprofile',
            name='start_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='experienceprofile',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='experienceprofile',
            name='start_date',
            field=models.DateField(),
        ),
    ]
