# Generated by Django 2.2.8 on 2020-01-03 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professional', '0008_auto_20191214_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='professional',
            name='position',
            field=models.CharField(blank=True, choices=[('P', 'Pilot'), ('C', 'Cabin Crew'), ('M', 'Maintenance'), ('O', 'Office')], max_length=2, null=True),
        ),
    ]
