# Generated by Django 2.2.8 on 2020-01-03 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('professional', '0009_professional_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionaldocs',
            name='pro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='professional.Professional'),
        ),
    ]
